language: node_js
node_js:
- 4
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2.4-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - gcc-4.8
    - g++-4.8
sudo: required
before_script: npm install
script:
- npm run test
- npm run lint
env:
  matrix:
  - CXX=g++-4.8
  - secure: XXGVE0toIy5yIq/bEnlDuvlK5i9lz/a6Pdw/3151pJCsGVRTVnXfF3vvRzzLneUOvP5HbTFDb2foV6K0jjYx/oy3II0M6KHI1skQYthni/W5pXhRIggMdy3KzwDv+WZmMyC2gmI6SXw6hw6jvnSXl+dvsPd4z4KFYz9/1SDRykSkBcXP2r5OHCJcRQ8Qo2X1WIh/RvpRP9gMJ0foqaS8LjUyKgvDZEJMRLD159YUuM0Z++KMIgTHBz011lzy1tMaFzVaW746LceH1zIigFzlj/GWqR7IWB5vkMkhMz9Xprvb5nyHDCWhtrRjdkczN/Wv9aMFF2vWRID3eDEb30Xk9u7tKjJsCFwFrALaPnzMvPN79Zkitz2O7pjrdx4VdecIJQz1DrUvnGdv6EHrJdoa0Xxjdrh4rliSdJdyTBdRH+b0y7kPJ9kxqp3idR0vOPAc10HST5nX5F4QDBQedTiBMbPggyQk9VdJP9JlsL18PLLoXQP5bWFchX+PM9wZAu0gXoWFsqBfQ7Xu5eEVAfG889I78g2kDs5PYeNWVY8Ihjy/5J5jxyd/eSKgwEtsE6vh1QYIePH3SbxGtGvaKnYWblMrKXbgnoyBoVWgk6mtDdNkJ+vUmgS2FO0lO5gU98wljonP9jfknJmvs9A/Cs3hGhjyrsRCllfP92axMvxnYkU=
  - secure: wDBKl4W35mjOIQV/k74RD7pn0KjvAPDUMZjxhaXlVYrq0bdcWuHWbkB9dzU+kk3fm5y0SOqA09Odcm7ciE75EuUpmUyyV9VBxH3TaHZqt3tyeozCcnHwvc5SZC9UpFFMni6YCb8uoyE1lKCaoFTWj5jXnrFbO1cXNBXy4EvVTCDl5WpwAEMo/xefdu7G/dKw/iOnI43dbUTo38ucQhwYFm1AVsYNenH8FsVhTEQc7eCCF0bs4O9bfHqw3X/XXHl7Jd9skqxMaC50zA79jGqJECXuYCPO6yJpUqNehvmoGZs7O+jTCL9QCoKuWk+ylRAWc7cp/uj2OCmBJWuFP9NkBMRxeylmRg+bQUpa24sfXGPCB5JUcKrkuI2hhW2WWePgsijVBfn2qH7MKglbTqTWnfxMJedgH6wqROy8ZgtVGcE2AxoH0VVRqNEV13cBBJ29G5Im4+g0iuaUfICFLeJMel5QkgoyOT276Lv62vxr0Urt3k5hvHQyuuGnxlkfIzf3NyC8JCsmpsCpfRvALJgqzO0yor/6+IlTK46Yoir09i40hSq3M9aO86lLtPNu8/UV8eCVgT6a1jEqz/8EB1pR7edt28AGwk2oTNUCkEP6asRtfkWBshx2SGKp+Vn0lvIbmItoa6IM69EI9IALGy8Zx0+AkE8RN8wKTAUJJlZk7CA=
  - secure: tk0Ew+AdaPb9w667hljFZMmN5Djr6h9rOAGX1w4wUHIBco+jPmOsCsPWaLY7p3iUO+BYL+AA0Qw5w4URSo5xVFX+cdnX+xy46HuyHDZJXKr1MUvyh4u29J0uJVZlz1CYFJH5SPmAFkWOKdFy9rcy4niRtkyK68GkaTkrEEYRW9T0+OQY5jg3E+m77rx1KNIHg6dO8N3kbPbN+NmUnW579fD4g6KFnkxF7MeargoiMx3Rg6xMJi+wyIxSBpJ5Gn3zd11ilYFezK6WuafTLn8NW1xOotA+A+XiDu4jfCQgkmyTHAMBCreqiOujICBS2eQj45SodyCprFKy7X1q47DFNzFiau07RA+Iaoz5B4H/gAaca3x+zTQ/T8uGFgdkJEMIjnBnVTSuOMj2Zii80UDQAoECQz8anZQHhkNbzrek+PIKZN6jGRGrQtAc2h7Nw31ko+SMFi2Xx/9vxeUxJD2pvBArFZCnHOeajnatQaflYQ4MuQgvv7iSmH7AC0rwwemLVfcumAGNOpx1g287bhe8NIrbFNtIwanJfYcGQJ/Clmk6HVJIfPbg3Zblq6sa6/vyLq5X+xqPs4DvGv7eUKufjLITUmlQhXlJhio6tq107gYIQwo02mDrM2XulIN24QgE41M8OkAaIBTZeTsEEpC5iwP2ZRr957J3KPfH3fbsJG4=
  - secure: UyfLGc+SFlTJICySVtme5RippPd/ZKyRm+KR6OEyGDMXe8vLoQ4PEAVQGQ9A6ma4S4zlzVu9rFQyf0L6XzhdFWdvmdVqR/Lmw6Nf9P0uRTFODKrIhXmKCmZQPNfkaoGVWE6rh/abdpvI05WTTFgFzeovLJ5DnLWri055V+D6/ZcAWgCXFAKywBpqucEJcej+xzpIcDBUUf36hT9OrDZED3Alux6bWQmSk/28pDkEcraqO0oeRpO58+dlzRBQYr2H9zEoY574Bbrn4qjoWC9gQCHofLhRAb19l30jzAqnbj4nbG+ItWLLQr443KC6pRt9xKZrcEhVX4k8pRGuHVNIcaLzwN8ng8MqFMHOI17sadokL9vFOEm4hZlqq/GQHAkwfYlEh5xXvttQ6Q498JnhTuvUh1c4SxQOczglZmimy0E12gOEhinp9eC3M/IfojWBZxa48jAdI2UKhO3B2CSjCMUVDL9/nXLsyJCZob3ZBemQID6mE0jgLjP+T1bDC3yvLaMIJRGvF4ucopEqzQd2rI0CP0knCpAfFrHcghIwiVNLe7N4mndzAOALuQzPTVNBawwEuogRC4nZCZZSd+p9gDizUS15NOXy/lr6mvxZFcQrYOVWPfcKfIJxthc8N1KEiJvpn9iZ4vJjdS9xx+rsI07iDQWBEoSvHrXlM56DFcc=
